language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
- PLONE_VERSION=4.2
- PLONE_VERSION=4.3
- PLONE_VERSION=5.0 TEST_EGGS=buildout:test-eggs=plone.app.contenttypes[test]
- PLONE_VERSION=5.1 TEST_EGGS=buildout:test-eggs=plone.app.contenttypes[test]
matrix:
  include:
  - python: 2.6
    env: PLONE_VERSION=4.0 PARTS=buildout:parts-=code-analysis
  - python: 2.6
    env: PLONE_VERSION=4.1 PARTS=buildout:parts-=code-analysis
  fast_finish: true
install:
- sed -ie "s#test-4.3.x.cfg#test-$PLONE_VERSION.x.cfg#" buildout.cfg
- python bootstrap.py
- bin/buildout $TEST_EGGS $PARTS $VERSIONS annotate
- bin/buildout $TEST_EGGS $PARTS $VERSIONS
script:
- test -x bin/code-analysis && bin/code-analysis || true
- bin/test
after_success:
- bin/createcoverage
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
